td/publishing/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView


from .views import (
    ajax_language_version,
    api_contact,
    ContactList,
    ContactCreate,
    ContactDetail,
    ContactUpdate,
    languages_autocomplete,
    OfficialResourceListView,
    OfficialResourceCreateView,
    OfficialResourceUpdateView,
    OfficialResourceDetailView,
    PublishRequestCreateView,
    PublishRequestUpdateView,
    PublishRequestDeleteView,
    source_languages_autocomplete,
)


urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="publishing/homepage.html"), name="publishing_home"),
    url(r"^api/contacts/", api_contact, name="api_contacts"),
    url(r"^contacts/$", ContactList.as_view(), name="contact_list"),
    url(r"^contacts/create/$", ContactCreate.as_view(), name="contact_create"),
    url(r"^contacts/(?P<pk>\d+)/$", ContactDetail.as_view(), name="contact_detail"),
    url(r"^contacts/(?P<pk>\d+)/update/$", ContactUpdate.as_view(), name="contact_update"),
    url(r"^oresource/$", OfficialResourceListView.as_view(), name="oresource_list"),
    url(r"^oresource/create/$", OfficialResourceCreateView.as_view(), name="oresource_create"),
    url(r"^oresource/(?P<pk>\d+)/$", OfficialResourceDetailView.as_view(), name="oresource_detail"),
    url(r"^oresource/(?P<code>[\w-]+)/update/$", OfficialResourceUpdateView.as_view(), name="oresource_update"),
    url(r"^publish/request/$", PublishRequestCreateView.as_view(), name="publish_request"),
    url(r"^publish/request/(?P<pk>\d+)", PublishRequestUpdateView.as_view(), name="publish_request_update"),
    url(r"^publish/request-reject/(?P<pk>\d+)", PublishRequestDeleteView.as_view(), name="publish_request_delete"),
    url(r"^ac/langnames/", languages_autocomplete, name="names_autocomplete"),
    url(r"^ac/src-langnames/", source_languages_autocomplete, name="source_names_autocomplete"),
    url(r"^ajax/langversion/", ajax_language_version, name="ajax_language_version")
)

td/resources/urls.py
from django.conf.urls import patterns, url

from .views import (
    PublisherListView,
    PublisherDetailView,
    PublisherEditView,
    PublisherCreateView,
    TitleListView,
    TitleDetailView,
    TitleEditView,
    TitleCreateView,
)

urlpatterns = patterns(
    "",
    url(r"publishers/$", PublisherListView.as_view(), name="publisher_list"),
    url(r"publishers/create/$", PublisherCreateView.as_view(), name="publisher_create"),
    url(r"publishers/(?P<pk>\d+)/$", PublisherDetailView.as_view(), name="publisher_detail"),
    url(r"publishers/(?P<pk>\d+)/edit/$", PublisherEditView.as_view(), name="publisher_edit"),
    url(r"titles/$", TitleListView.as_view(), name="title_list"),
    url(r"titles/create/$", TitleCreateView.as_view(), name="title_create"),
    url(r"titles/(?P<slug>[-\w\d]+)/$", TitleDetailView.as_view(), name="title_detail"),
    url(r"titles/(?P<slug>[-\w\d]+)/edit/$", TitleEditView.as_view(), name="title_edit"),
)

td/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin

from .views import (
    AdditionalLanguageListView,
    EthnologueCountryCodeListView,
    EthnologueLanguageCodeListView,
    EthnologueLanguageIndexListView,
    SIL_ISO_639_3ListView,
    WikipediaISOLanguageListView,
    IMBPeopleGroupListView,
    AjaxAdditionalLanguageListView,
    AjaxEthnologueCountryCodeListView,
    AjaxEthnologueLanguageCodeListView,
    AjaxEthnologueLanguageIndexListView,
    AjaxSIL_ISO_639_3ListView,
    AjaxWikipediaISOLanguageListView,
    AjaxIMBPeopleGroupListView
)

urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^siteadmin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^invites/", include("kaleo.urls")),

    url(r"^exports/codes-d43.txt$", "td.views.codes_text_export", name="codes_text_export"),
    url(r"^exports/langnames.txt$", "td.views.names_text_export", name="names_text_export"),
    url(r"^exports/langnames.json$", "td.views.names_json_export", name="names_json_export"),
    url(r"^exports/gatewaylanguages-map/$", "td.views.export_svg", name="gateway_languages_map_export"),

    url(r"^uw/", include("td.resources.urls")),
    url(r"^uw/", include("td.urls_languages")),

    url(r"^publishing/", include("td.publishing.urls")),

    url(r"^data-sources/additional-languages/$", AdditionalLanguageListView.as_view(), name="ds_additional_languages"),
    url(r"^data-sources/ethnologue/country-codes/$", EthnologueCountryCodeListView.as_view(), name="ds_ethnologue_country_codes"),
    url(r"^data-sources/ethnologue/language-codes/$", EthnologueLanguageCodeListView.as_view(), name="ds_ethnologue_language_codes"),
    url(r"^data-sources/ethnologue/language-index/$", EthnologueLanguageIndexListView.as_view(), name="ds_ethnologue_language_index"),
    url(r"^data-sources/sil-iso-639-3/$", SIL_ISO_639_3ListView.as_view(), name="ds_sil"),
    url(r"^data-sources/wikipedia/$", WikipediaISOLanguageListView.as_view(), name="ds_wikipedia"),
    url(r"^data-sources/imb/peoplegroups/$", IMBPeopleGroupListView.as_view(), name="ds_imb_peoplegroups"),

    url(r"^ajax/data-sources/additional-languages/$", AjaxAdditionalLanguageListView.as_view(), name="ajax_ds_additional_languages"),
    url(r"^ajax/data-sources/ethnologue/country-codes/$", AjaxEthnologueCountryCodeListView.as_view(), name="ajax_ds_ethnologue_country_codes"),
    url(r"^ajax/data-sources/ethnologue/language-codes/$", AjaxEthnologueLanguageCodeListView.as_view(), name="ajax_ds_ethnologue_language_codes"),
    url(r"^ajax/data-sources/ethnologue/language-index/$", AjaxEthnologueLanguageIndexListView.as_view(), name="ajax_ds_ethnologue_language_index"),
    url(r"^ajax/data-sources/sil-iso-639-3/$", AjaxSIL_ISO_639_3ListView.as_view(), name="ajax_ds_sil"),
    url(r"^ajax/data-sources/wikipedia/$", AjaxWikipediaISOLanguageListView.as_view(), name="ajax_ds_wikipedia"),
    url(r"^ajax/data-sources/imb/peoplegroups/$", AjaxIMBPeopleGroupListView.as_view(), name="ajax_ds_imb_peoplegroups"),

    url(r"^ac/langnames/", "td.views.languages_autocomplete", name="names_autocomplete"),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

td/models.py
from collections import defaultdict
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from jsonfield import JSONField
from model_utils import FieldTracker


@python_2_unicode_compatible
class AdditionalLanguage(models.Model):
    DIRECTION_CHOICES = (
        ("l", "ltr"),
        ("r", "rtl")
    )
    ietf_tag = models.CharField(max_length=100)
    common_name = models.CharField(max_length=100)
    two_letter = models.CharField(max_length=2, blank=True)
    three_letter = models.CharField(max_length=3, blank=True)
    native_name = models.CharField(max_length=100, blank=True)
    direction = models.CharField(max_length=1, choices=DIRECTION_CHOICES, default="l")
    comment = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def merge_code(self):
        return self.two_letter or self.three_letter or self.ietf_tag

    def merge_name(self):
        return self.native_name or self.common_name

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        return super(AdditionalLanguage, self).save(*args, **kwargs)

    def __str__(self):
        return self.ietf_tag

    class Meta:
        verbose_name = "Additional Language"


@python_2_unicode_compatible
class Network(models.Model):
    name = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("network_detail", args=[self.pk])

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'uw_network'


@python_2_unicode_compatible
class Region(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    tracker = FieldTracker()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'uw_region'
        ordering = ['name']


@python_2_unicode_compatible
class Country(models.Model):
    code = models.CharField(max_length=2, unique=True)
    alpha_3_code = models.CharField(max_length=3, blank=True, default="")
    name = models.CharField(max_length=75)
    region = models.ForeignKey(Region, null=True, blank=True, related_name="countries")
    population = models.IntegerField(null=True, blank=True)
    primary_networks = models.ManyToManyField(Network, blank=True, db_table='uw_country_primary_networks')
    extra_data = JSONField(blank=True)

    tracker = FieldTracker()

    class Meta:
        db_table = 'uw_country'

    def gateway_language(self):
        if not hasattr(self, "_gateway_language"):
            data = self.extra_data
            if not isinstance(data, dict):
                data = {}
            self._gateway_language = next(iter(Language.objects.filter(code=data.get("gateway_language"))), None)
        return self._gateway_language

    def gateway_languages(self, with_primary=True):
        gl = self.gateway_language()
        if gl:
            ogls = [gl]
        else:
            ogls = []
        for lang in self.language_set.all():
            if lang.gateway_flag and lang not in ogls:
                ogls.append(lang)
            elif lang.gateway_language and lang.gateway_language not in ogls:
                ogls.append(lang.gateway_language)
        if not with_primary and gl:
            ogls.remove(gl)
        return ogls

    @classmethod
    def regions(cls):
        qs = cls.objects.all().values_list("region", flat=True).distinct()
        qs = qs.order_by("region.name")
        return qs

    @classmethod
    def gateway_data(cls):
        with_gateways = cls.objects.filter(language__gateway_language__isnull=False).distinct()
        without_gateways = cls.objects.exclude(pk__in=with_gateways)
        data = {
            x.code: {"obj": x, "gateways": defaultdict(lambda: [])}
            for x in with_gateways
        }
        data.update({
            x.code: {"obj": x, "gateways": {"n/a": list(x.language_set.all())}}
            for x in without_gateways
        })
        for country in with_gateways:
            for lang in country.language_set.all():
                if lang.gateway_language:
                    data[country.code]["gateways"][lang.gateway_language.code].append(lang)
                else:
                    data[country.code]["gateways"]["n/a"].append(lang)
        return data

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Language(models.Model):
    DIRECTION_CHOICES = (
        ("l", "ltr"),
        ("r", "rtl")
    )
    code = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    gateway_language = models.ForeignKey("self", related_name="gateway_to", null=True, blank=True)
    native_speakers = models.IntegerField(null=True, blank=True)
    networks_translating = models.ManyToManyField(Network, blank=True, db_table='uw_language_networks_translating')
    gateway_flag = models.BooleanField(default=False, blank=True, db_index=True)
    direction = models.CharField(max_length=1, choices=DIRECTION_CHOICES, default="l")
    iso_639_3 = models.CharField(max_length=3, default="", db_index=True, blank=True, verbose_name="ISO-639-3")
    extra_data = JSONField(blank=True)

    tracker = FieldTracker()

    class Meta:
        db_table = 'uw_language'

    def __str__(self):
        return self.name

    @property
    def cc(self):
        if self.country:
            return self.country.code.encode("utf-8")
        return ""

    @property
    def lr(self):
        if self.country and self.country.region:
            return self.country.region.name.encode("utf-8")
        return ""

    @property
    def lc(self):
        return self.code

    @property
    def ln(self):
        return self.name.encode("utf-8")

    @classmethod
    def codes_text(cls):
        return " ".join([
            x.code
            for x in cls.objects.all().order_by("code")
        ])

    @classmethod
    def names_text(cls):
        return "\n".join([
            "{}\t{}".format(x.code, x.name.encode("utf-8"))
            for x in cls.objects.all().order_by("code")
        ])

    @classmethod
    def names_data(cls):
        return [
            dict(pk=x.pk, lc=x.lc, ln=x.ln, cc=[x.cc], lr=x.lr, gw=x.gateway_flag, ld=x.get_direction_display())
            for x in cls.objects.all().order_by("code")
        ]


class EAVBase(models.Model):
    attribute = models.CharField(max_length=100)
    value = models.CharField(max_length=250)
    source_ct = models.ForeignKey(ContentType)
    source_id = models.IntegerField()
    timestamp = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True


class CountryEAV(EAVBase):
    entity = models.ForeignKey(Country, related_name="attributes")

    class Meta:
        db_table = 'uw_countryeav'


class LanguageEAV(EAVBase):
    entity = models.ForeignKey(Language, related_name="attributes")

    class Meta:
        db_table = 'uw_languageeav'

td/resources/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView, TemplateView
from account.mixins import LoginRequiredMixin

from pinax.eventlog.mixins import EventLogMixin
from .forms import (
    ResourceForm,
    TitleForm,
    PublisherForm
)
from .models import (
    Resource,
    Title,
    Publisher
)
from td.models import Language


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "resources/home.html"


class EntityTrackingMixin(object):

    def get_form_kwargs(self):
        kwargs = super(EntityTrackingMixin, self).get_form_kwargs()
        kwargs.update({
            "source": self.request.user
        })
        return kwargs


class PublisherListView(ListView):
    model = Publisher

    def get_queryset(self):
        qs = super(PublisherListView, self).get_queryset()
        qs = qs.order_by("name")
        return qs


class PublisherDetailView(DetailView):
    model = Publisher


class PublisherEditView(LoginRequiredMixin, EventLogMixin, UpdateView):
    model = Publisher
    form_class = PublisherForm
    action_kind = "EDIT"

    def get_success_url(self):
        return reverse("publisher_detail", args=[self.object.pk])


class PublisherCreateView(LoginRequiredMixin, EventLogMixin, CreateView):
    model = Publisher
    form_class = PublisherForm
    action_kind = "CREATE"

    def get_success_url(self):
        return reverse("publisher_detail", args=[self.object.pk])


class TitleListView(ListView):
    model = Title

    def get_queryset(self):
        qs = super(TitleListView, self).get_queryset()
        qs = qs.order_by("name")
        return qs


class TitleDetailView(DetailView):
    model = Title


class TitleEditView(LoginRequiredMixin, EventLogMixin, UpdateView):
    model = Title
    form_class = TitleForm
    action_kind = "EDIT"

    def get_success_url(self):
        return reverse("title_detail", args=[self.object.slug])


class TitleCreateView(LoginRequiredMixin, EventLogMixin, CreateView):
    model = Title
    form_class = TitleForm
    action_kind = "CREATE"

    def get_success_url(self):
        return reverse("title_detail", args=[self.object.slug])


class ResourceCreateView(LoginRequiredMixin, CreateView):
    model = Resource
    form_class = ResourceForm
    action_kind = "CREATE"

    def dispatch(self, request, *args, **kwargs):
        self.language = get_object_or_404(Language, pk=self.kwargs.get("pk"))
        return super(ResourceCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.language = self.language
        self.object.save()
        return redirect("language_detail", self.language.pk)

    def get_context_data(self, **kwargs):
        context = super(ResourceCreateView, self).get_context_data(**kwargs)
        context.update({
            "language": self.language
        })
        return context


class ResourceEditView(LoginRequiredMixin, UpdateView):
    model = Resource
    form_class = ResourceForm
    action_kind = "EDIT"

    def get_success_url(self):
        print self.object.language.pk
        return reverse("language_detail", args=[self.object.language.pk])

    def get_context_data(self, **kwargs):
        context = super(ResourceEditView, self).get_context_data(**kwargs)
        context.update({
            "language": self.object.language,
        })
        return context

td/templates/resources/_breadcrumbs.html
<ol class="breadcrumb">
    {% if region %}
        <li><a href="{% url "region_list" %}">Regions</a></li>
        {% if country %}
            <li><a href="{% url "region_detail" region.slug|lower %}">{{ region.name }}</a></li>
        {% else %}
            <li class="active">{{ region.name }}</li>
        {% endif %}
    {% endif %}
    {% if country_form %}
        <li class="active">{% if form.instance.pk %}Edit{% else %}Add{% endif %} {{ country.name }}</li>
    {% elif country %}
        {% if language %}
            <li><a href="{% url "country_detail" country.pk %}">{{ country.name }}</a></li>
        {% else %}
            <li class="active">{{ country.name }}</li>
        {% endif %}
    {% endif %}
    {% if language_form %}
        <li class="active">{% if language_form.instance.pk %}Edit {{ language_form.instance.name }}{% else %}Add Language{% endif %}</li>
    {% elif language %}
        {% if resource_form %}
            <li><a href="{% url "language_detail" language.pk %}">{{ language.name }}</a></li>
        {% else %}
            <li class="active">{{ language.name }}</li>
        {% endif %}
    {% endif %}
    {% if resource_form %}
        <li class="active">{% if form.instance.pk %}Edit{% else %}Add{% endif %} Resource</li>
    {% endif %}
</ol>

td/templates/resources/_country_list.html
{% load humanize %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Country</th>
            <th>Population</th>
            <th>Primary Networks</th>
        </tr>
    </thead>
    <tbody>
        {% for country in country_list %}
            <tr>
                <td><a href="{% url "country_detail" country.pk %}">{{ country.name }}</a></td>
                <td class="text-right">{{ country.population|default:""|intcomma }}</td>
                <td>
                    {% for network in country.primary_networks.all %}
                        <a href="{{ network.get_absolute_url }}">{{ network }}</a>{% if forloop.last %}{% else %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

td/templates/resources/_language_list.html
{% load humanize %}
<table class="table">
    <thead><tr><th></th><th>Language</th><th>Is Gateway</th><th>Gateway Language</th><th># of Native Speakers</th><th>Networks Translating</th></tr></thead>
    <tbody>
        {% for language in language_list %}
            <tr>
                <td>
                    {% if user.is_authenticated %}
                    <a class="btn btn-default btn-xs" href="{% url "language_edit" language.pk %}"><i class="fa fa-fw fa-pencil"></i> Edit</a>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url "language_detail" language.pk %}">
                        {{ language.name }} ({{ language.code }})
                    </a>
                </td>
                <td>{% if language.gateway_flag %}<i class="fa fa-check fa-lg"></i>{% endif %}</td>
                <td>{% if language.gateway_language %}{{ language.gateway_language.name }} ({{ language.gateway_language.code }}){% endif %}</td>
                <td>{{ language.native_speakers|default:""|intcomma }}</td>
                <td>
                    {% for network in language.networks_translating.all %}
                        <a href="{{ network.get_absolute_url }}">{{ network }}</a>{% if forloop.last %}{% else %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

td/templates/resources/_short_list.html
<table class="table">
    <thead><tr><th>{{ title }}</th></tr></thead>
    <tbody>
    {% for d in data %}
        <tr><td><a href="{{ d.get_absolute_url }}">{{ d }}</a></td></tr>
    {% endfor %}
    </tbody>
</table>

td/templates/resources/country_detail.html
{% extends "site_base.html" %}

{% load humanize %}

{% block body %}

    {% include "resources/_breadcrumbs.html" with region=country.region %}

<h1>
  {{ country.name }}
    {% if user.is_authenticated %}
        <a class="btn btn-primary btn-xs" href="{% url "country_edit" country.pk %}">Edit</a>
    {% endif %}
</h1>



<div class="row">
    <div class="col-md-4">
        <table class="table">
            <thead><tr><th>Gateway Language</th></tr></thead>
            <tbody><tr><td>{% if country.gateway_language %}{{ country.gateway_language.name }} ({{ country.gateway_language.code }}){% else %}None{% endif %}</td></tr></tbody>
        </table>
    </div>
    <div class="col-md-4">
        <table class="table">
            <thead><tr><th>Population</th></tr></thead>
            <tbody><tr><td>{{ country.population|default:""|intcomma }}</td></tr></tbody>
        </table>
    </div>
    <div class="col-md-4">
        {% include "resources/_short_list.html" with title="Top Networks" data=country.primary_networks.all %}
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">
        {% if user.is_authenticated %}
        <a class="btn btn-primary btn-xs pull-right" href="{% url "language_create" country.pk %}"><i class="fa fa-plus"></i> Add</a>
        {% endif %}
        <h2 class="panel-title">Languages</h2>
    </div>
    {% include "resources/_language_list.html" with language_list=country.language_set.all %}
</div>

{% endblock %}

td/templates/resources/language_form.html
{% extends "site_base.html" %}

{% load humanize bootstrap %}

{% block body %}
    {% include "resources/_breadcrumbs.html" with language_form=form region=country.region %}

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">{% if form.instance.pk %}Edit {{ form.instance.name }}{% else %}Add Language{% endif %}</h1>
            </div>
            <div class="panel-body">
                <form class="form" action="." method="POST">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="pull-right">
                        {% if form.instance.pk %}
                            {% url "language_detail" language.pk as cancel_url %}
                        {% else %}
                            {% url "country_detail" country.pk as cancel_url %}
                        {% endif %}
                        <a class="btn btn-default" href="{{ cancel_url }}">Cancel</a>
                        <button class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

td/templates/resources/network_detail.html
{% extends "site_base.html" %}

{% load humanize %}

{% block body %}
<ol class="breadcrumb">
  <li><a href="{% url "network_list" %}">Networks</a></li>
  <li class="active">{{ network.name }}</li>
</ol>

<h1>
    {{ network.name }}
    {% if user.is_authenticated %}
    <a class="btn btn-primary btn-xs" href="{% url "network_edit" network.pk %}"><i class="fa fa-pencil"></i> Edit</a>
    {% endif %}
</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Languages</h2>
    </div>
    {% include "resources/_language_list.html" with language_list=network.language_set.all %}
</div>


<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Countries</h2>
    </div>
    {% include "resources/_country_list.html" with country_list=network.country_set.all %}
</div>
{% endblock %}

td/templates/resources/network_form.html
{% extends "site_base.html" %}

{% load humanize bootstrap %}

{% block body %}
<ol class="breadcrumb">
  <li><a href="{% url "network_list" %}">Networks</a></li>
  {% if network %}<li><a href="{% url "network_detail" network.pk %}">{{ network.name }}</a></li> {% endif %}
  <li class="active">{% if form.instance.pk %}Edit {{ network.name }}{% else %}Add Network{% endif %}</li>
</ol>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">{% if form.instance.pk %}Edit {{ network.name }}{% else %}Add Network{% endif %}</h1>
            </div>
            <div class="panel-body">
                <form class="form" action="." method="POST">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="pull-right">
                        {% if form.instance.pk %}
                            {% url "network_detail" form.instance.pk as cancel_url %}
                        {% else %}
                            {% url "network_list" as cancel_url %}
                        {% endif %}
                        <a class="btn btn-default" href="{{ cancel_url }}">Cancel</a>
                        <button class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

td/templates/resources/network_list.html
{% extends "site_base.html" %}

{% load humanize %}

{% block body %}

    <div class="panel panel-default">
        <div class="panel-heading">
            {% if user.is_authenticated %}
            <a class="btn btn-primary pull-right btn-xs" href="{% url "network_create" %}">
                <i class="fa fa-plus"></i>
                Add
            </a>
            {% endif %}
            <h1 class="panel-title">Networks</h1>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th></th>
                    <th>Network</th>
                    <th>Countries</th>
                    <th>Languages</th>
                </tr>
            </thead>
            <tbody>
                {% for network in network_list %}
                    <tr>
                        <td>{% if user.is_authenticated %}<a class="btn btn-default btn-xs" href="{% url "network_edit" network.pk %}"><i class="fa fa-pencil"></i> Edit</a>{% endif %}</td>
                        <td><a href="{% url "network_detail" network.pk %}">{{ network.name }}</a></td>
                        <td>{{ network.country_set.all|join:", " }}</td>
                        <td>{{ network.language_set.all|join:", "}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

td/templates/resources/region_detail.html
{% extends "site_base.html" %}

{% load humanize %}

{% block body %}
    {% include "resources/_breadcrumbs.html" %}

    <h1>{{ region.name }}</h1>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Countries</h2>
        </div>
        {% include "resources/_country_list.html" %}
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Languages</h2>
        </div>
        {% include "resources/_language_list.html" with language_list=languages %}
    </div>
{% endblock %}

td/templates/resources/region_list.html
{% extends "site_base.html" %}

{% load humanize %}

{% block body %}
    <h1>Regions</h1>
    <ul>
        {% for region in region_list %}
            <li><a href="{% url "region_detail" region.slug|lower %}">{{ region }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}