td/publishing/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView


from .views import (
    ajax_language_version,
    api_contact,
    ContactList,
    ContactCreate,
    ContactDetail,
    ContactUpdate,
    languages_autocomplete,
    OfficialResourceListView,
    OfficialResourceCreateView,
    OfficialResourceUpdateView,
    OfficialResourceDetailView,
    PublishRequestCreateView,
    PublishRequestUpdateView,
    PublishRequestDeleteView,
    source_languages_autocomplete,
)


urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="publishing/homepage.html"), name="publishing_home"),
    url(r"^api/contacts/", api_contact, name="api_contacts"),
    url(r"^contacts/$", ContactList.as_view(), name="contact_list"),
    url(r"^contacts/create/$", ContactCreate.as_view(), name="contact_create"),
    url(r"^contacts/(?P<pk>\d+)/$", ContactDetail.as_view(), name="contact_detail"),
    url(r"^contacts/(?P<pk>\d+)/update/$", ContactUpdate.as_view(), name="contact_update"),
    url(r"^oresource/$", OfficialResourceListView.as_view(), name="oresource_list"),
    url(r"^oresource/create/$", OfficialResourceCreateView.as_view(), name="oresource_create"),
    url(r"^oresource/(?P<pk>\d+)/$", OfficialResourceDetailView.as_view(), name="oresource_detail"),
    url(r"^oresource/(?P<code>[\w-]+)/update/$", OfficialResourceUpdateView.as_view(), name="oresource_update"),
    url(r"^publish/request/$", PublishRequestCreateView.as_view(), name="publish_request"),
    url(r"^publish/request/(?P<pk>\d+)", PublishRequestUpdateView.as_view(), name="publish_request_update"),
    url(r"^publish/request-reject/(?P<pk>\d+)", PublishRequestDeleteView.as_view(), name="publish_request_delete"),
    url(r"^ac/langnames/", languages_autocomplete, name="names_autocomplete"),
    url(r"^ac/src-langnames/", source_languages_autocomplete, name="source_names_autocomplete"),
    url(r"^ajax/langversion/", ajax_language_version, name="ajax_language_version")
)

td/resources/urls.py
from django.conf.urls import patterns, url

from .views import (
    PublisherListView,
    PublisherDetailView,
    PublisherEditView,
    PublisherCreateView,
    TitleListView,
    TitleDetailView,
    TitleEditView,
    TitleCreateView,
)

urlpatterns = patterns(
    "",
    url(r"publishers/$", PublisherListView.as_view(), name="publisher_list"),
    url(r"publishers/create/$", PublisherCreateView.as_view(), name="publisher_create"),
    url(r"publishers/(?P<pk>\d+)/$", PublisherDetailView.as_view(), name="publisher_detail"),
    url(r"publishers/(?P<pk>\d+)/edit/$", PublisherEditView.as_view(), name="publisher_edit"),
    url(r"titles/$", TitleListView.as_view(), name="title_list"),
    url(r"titles/create/$", TitleCreateView.as_view(), name="title_create"),
    url(r"titles/(?P<slug>[-\w\d]+)/$", TitleDetailView.as_view(), name="title_detail"),
    url(r"titles/(?P<slug>[-\w\d]+)/edit/$", TitleEditView.as_view(), name="title_edit"),
)

td/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin

from .views import (
    AdditionalLanguageListView,
    EthnologueCountryCodeListView,
    EthnologueLanguageCodeListView,
    EthnologueLanguageIndexListView,
    SIL_ISO_639_3ListView,
    WikipediaISOLanguageListView,
    IMBPeopleGroupListView,
    AjaxAdditionalLanguageListView,
    AjaxEthnologueCountryCodeListView,
    AjaxEthnologueLanguageCodeListView,
    AjaxEthnologueLanguageIndexListView,
    AjaxSIL_ISO_639_3ListView,
    AjaxWikipediaISOLanguageListView,
    AjaxIMBPeopleGroupListView
)

urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^siteadmin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^invites/", include("kaleo.urls")),

    url(r"^exports/codes-d43.txt$", "td.views.codes_text_export", name="codes_text_export"),
    url(r"^exports/langnames.txt$", "td.views.names_text_export", name="names_text_export"),
    url(r"^exports/langnames.json$", "td.views.names_json_export", name="names_json_export"),
    url(r"^exports/gatewaylanguages-map/$", "td.views.export_svg", name="gateway_languages_map_export"),

    url(r"^uw/", include("td.resources.urls")),
    url(r"^uw/", include("td.urls_languages")),

    url(r"^publishing/", include("td.publishing.urls")),

    url(r"^data-sources/additional-languages/$", AdditionalLanguageListView.as_view(), name="ds_additional_languages"),
    url(r"^data-sources/ethnologue/country-codes/$", EthnologueCountryCodeListView.as_view(), name="ds_ethnologue_country_codes"),
    url(r"^data-sources/ethnologue/language-codes/$", EthnologueLanguageCodeListView.as_view(), name="ds_ethnologue_language_codes"),
    url(r"^data-sources/ethnologue/language-index/$", EthnologueLanguageIndexListView.as_view(), name="ds_ethnologue_language_index"),
    url(r"^data-sources/sil-iso-639-3/$", SIL_ISO_639_3ListView.as_view(), name="ds_sil"),
    url(r"^data-sources/wikipedia/$", WikipediaISOLanguageListView.as_view(), name="ds_wikipedia"),
    url(r"^data-sources/imb/peoplegroups/$", IMBPeopleGroupListView.as_view(), name="ds_imb_peoplegroups"),

    url(r"^ajax/data-sources/additional-languages/$", AjaxAdditionalLanguageListView.as_view(), name="ajax_ds_additional_languages"),
    url(r"^ajax/data-sources/ethnologue/country-codes/$", AjaxEthnologueCountryCodeListView.as_view(), name="ajax_ds_ethnologue_country_codes"),
    url(r"^ajax/data-sources/ethnologue/language-codes/$", AjaxEthnologueLanguageCodeListView.as_view(), name="ajax_ds_ethnologue_language_codes"),
    url(r"^ajax/data-sources/ethnologue/language-index/$", AjaxEthnologueLanguageIndexListView.as_view(), name="ajax_ds_ethnologue_language_index"),
    url(r"^ajax/data-sources/sil-iso-639-3/$", AjaxSIL_ISO_639_3ListView.as_view(), name="ajax_ds_sil"),
    url(r"^ajax/data-sources/wikipedia/$", AjaxWikipediaISOLanguageListView.as_view(), name="ajax_ds_wikipedia"),
    url(r"^ajax/data-sources/imb/peoplegroups/$", AjaxIMBPeopleGroupListView.as_view(), name="ajax_ds_imb_peoplegroups"),

    url(r"^ac/langnames/", "td.views.languages_autocomplete", name="names_autocomplete"),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

td/publishing/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

import reversion

from td.models import Language


class Organization(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of Organization")
    email = models.CharField(max_length=255, blank=True, verbose_name="Email address")
    phone = models.CharField(max_length=255, blank=True, verbose_name="Phone number")
    website = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    languages = models.ManyToManyField(Language, related_name="organizations")
    other = models.TextField(blank=True, verbose_name="Other information")
    checking_entity = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of contact")
    email = models.CharField(max_length=255, blank=True, verbose_name="Email address")
    d43username = models.CharField(max_length=255, blank=True, verbose_name="Door43 username")
    location = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255, blank=True, verbose_name="Phone number")
    languages = models.ManyToManyField(Language, related_name="contacts")
    org = models.ManyToManyField(Organization, blank=True, verbose_name="organizations")
    other = models.TextField(blank=True, verbose_name="Other information")

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class ConnectionType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of Connection Type")
    mutual = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Connection(models.Model):
    con_src = models.ForeignKey(Contact, related_name="source_connections")
    con_dst = models.ForeignKey(Contact, related_name="destination_connections", verbose_name="Connection")
    con_type = models.ForeignKey(ConnectionType, verbose_name="Type")

    class Meta:
        ordering = ["con_src"]

    def __unicode__(self):
        return self.con_src.name


class RecentCommunication(models.Model):
    contact = models.ForeignKey(Contact, related_name="recent_communications")
    communication = models.TextField(blank=True, verbose_name="Message")
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        ordering = ["contact", "created"]

    def __unicode__(self):
        return self.contact.name


CHECKING_LEVEL_CHOICES = [
    (1, "1"),
    (2, "2"),
    (3, "3"),
]


@python_2_unicode_compatible
class OfficialResourceType(models.Model):
    short_name = models.CharField(max_length=5, help_text="a 5 character identification code")
    long_name = models.CharField(max_length=50, help_text="a more descriptive name")
    description = models.TextField(blank=True)

    def __str__(self):
        return "({0}) {1}".format(self.short_name, self.long_name)


@reversion.register()
class OfficialResource(models.Model):
    language = models.ForeignKey(Language, related_name="official_resources", verbose_name="Language")
    resource_type = models.ForeignKey(OfficialResourceType, verbose_name="official_resources")
    contact = models.ForeignKey(Contact, related_name="official_resources", null=True, blank=True)
    date_started = models.DateField()
    notes = models.TextField(blank=True)
    offline = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    # Publishing
    publish_date = models.DateField(null=True, blank=True)
    version = models.CharField(max_length=10, blank=True)
    source_text = models.ForeignKey(Language, null=True, blank=True, related_name="+")
    source_version = models.CharField(max_length=10, blank=True)
    checking_entity = models.ManyToManyField(Organization, related_name="resource_publications", blank=True)
    contributors = models.ManyToManyField(Contact, related_name="+", blank=True)
    checking_level = models.IntegerField(choices=CHECKING_LEVEL_CHOICES, null=True, blank=True)

    def versions(self):
        return reversion.get_for_object(self)

    class Meta:
        ordering = ["language", "contact"]

    def __unicode__(self):
        return self.language.code


class Comment(models.Model):
    official_resource = models.ForeignKey(OfficialResource, related_name="comments", null=True)
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)


@python_2_unicode_compatible
class PublishRequest(models.Model):
    requestor = models.CharField(max_length=100, verbose_name="Requester name")
    resource_type = models.ForeignKey(OfficialResourceType, null=True)
    language = models.ForeignKey(Language, related_name="publish_requests")
    checking_level = models.IntegerField(choices=CHECKING_LEVEL_CHOICES, verbose_name="Requested checking level")
    source_text = models.ForeignKey(Language, related_name="source_publish_requests", null=True)
    source_version = models.CharField(max_length=10, blank=True)
    contributors = models.TextField(blank=True, help_text="Names or Pseudonyms")
    created_at = models.DateTimeField(default=timezone.now)
    approved_at = models.DateTimeField(default=None, blank=True, null=True, db_index=True)
    requestor_email = models.EmailField(blank=True,
                                        default="",
                                        verbose_name="Requester email",
                                        help_text="email address to be notified of request status")

    def __str__(self):
        return "({0}) for {1} in language: {2}".format(str(self.pk), str(self.get_resource_display()), self.language)


class LicenseAgreement(models.Model):
    publish_request = models.ForeignKey(PublishRequest)
    document = models.FileField(upload_to="agreements/")

td/resources/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView, TemplateView
from account.mixins import LoginRequiredMixin

from pinax.eventlog.mixins import EventLogMixin
from .forms import (
    ResourceForm,
    TitleForm,
    PublisherForm
)
from .models import (
    Resource,
    Title,
    Publisher
)
from td.models import Language


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "resources/home.html"


class EntityTrackingMixin(object):

    def get_form_kwargs(self):
        kwargs = super(EntityTrackingMixin, self).get_form_kwargs()
        kwargs.update({
            "source": self.request.user
        })
        return kwargs


class PublisherListView(ListView):
    model = Publisher

    def get_queryset(self):
        qs = super(PublisherListView, self).get_queryset()
        qs = qs.order_by("name")
        return qs


class PublisherDetailView(DetailView):
    model = Publisher


class PublisherEditView(LoginRequiredMixin, EventLogMixin, UpdateView):
    model = Publisher
    form_class = PublisherForm
    action_kind = "EDIT"

    def get_success_url(self):
        return reverse("publisher_detail", args=[self.object.pk])


class PublisherCreateView(LoginRequiredMixin, EventLogMixin, CreateView):
    model = Publisher
    form_class = PublisherForm
    action_kind = "CREATE"

    def get_success_url(self):
        return reverse("publisher_detail", args=[self.object.pk])


class TitleListView(ListView):
    model = Title

    def get_queryset(self):
        qs = super(TitleListView, self).get_queryset()
        qs = qs.order_by("name")
        return qs


class TitleDetailView(DetailView):
    model = Title


class TitleEditView(LoginRequiredMixin, EventLogMixin, UpdateView):
    model = Title
    form_class = TitleForm
    action_kind = "EDIT"

    def get_success_url(self):
        return reverse("title_detail", args=[self.object.slug])


class TitleCreateView(LoginRequiredMixin, EventLogMixin, CreateView):
    model = Title
    form_class = TitleForm
    action_kind = "CREATE"

    def get_success_url(self):
        return reverse("title_detail", args=[self.object.slug])


class ResourceCreateView(LoginRequiredMixin, CreateView):
    model = Resource
    form_class = ResourceForm
    action_kind = "CREATE"

    def dispatch(self, request, *args, **kwargs):
        self.language = get_object_or_404(Language, pk=self.kwargs.get("pk"))
        return super(ResourceCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.language = self.language
        self.object.save()
        return redirect("language_detail", self.language.pk)

    def get_context_data(self, **kwargs):
        context = super(ResourceCreateView, self).get_context_data(**kwargs)
        context.update({
            "language": self.language
        })
        return context


class ResourceEditView(LoginRequiredMixin, UpdateView):
    model = Resource
    form_class = ResourceForm
    action_kind = "EDIT"

    def get_success_url(self):
        print self.object.language.pk
        return reverse("language_detail", args=[self.object.language.pk])

    def get_context_data(self, **kwargs):
        context = super(ResourceEditView, self).get_context_data(**kwargs)
        context.update({
            "language": self.object.language,
        })
        return context

td/templates/publishing/_oresource_row_data.html
<td>
    {% if not version %}
        <a href="{% url "oresource_update" oresource.language.code %}" class="btn btn-xs btn-default">
            <i class="fa fa-pencil"></i>
            Edit
        </a>
    {% endif %}
</td>
<td class="language">
    {% if not version %}
        <a href="{% url "oresource_detail" oresource.pk %}">
            {{ oresource.language.name }} ({{ oresource.language.code }})
        </a>
        <br />
    {% endif %}
    <small class="text-muted">
        {% if version %}{{ version.revision.date_created }} / {{ version.revision.user }}{% else %}{{ oresource.created }} / {{ oresource.created_by }}{% endif %}
    </small>
</td>
<td>{{ oresource.contqct }}</td>
<td>{{ oresource.date_started }}</td>
<td>{{ oresource.notes }}</td>
<td>{% if oresource.offline %}<i class="fa fa-fw fa-check"></i>{% endif %}</td>
<td>{{ oresource.publish_date|default:"" }}</td>
<td>{{ oresource.version|default:"" }}</td>
<td>
    {% if oresource.source_text %}{{ oresource.source_text }}{% endif %}
    {% if oresource.source_version %} v{{ oresource.source_version }}{% endif %}
</td>
<td>{% for c in oresource.checking_entity.all %}{{ c.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
<td>{{ oresource.checking_level|default:"" }}</td>

td/templates/publishing/_pr_row_data.html
<td>
    <a href="{% url "publish_request_update" pr.pk %}" class="btn btn-xs btn-primary">Review</a>
</td>
<td>
    {{ pr.requestor }}
</td>
<td>
    {{ pr.resource_type }}
</td>
<td>
    {{ pr.language }}
</td>
<td>
    {{ pr.checking_level }}
</td>
<td>
    {{ pr.contributors }}
</td>
<td>
    {{ pr.created_at }}
</td>

td/templates/publishing/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Home{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}uW Admin{% endblocktrans %}</h1>
            {% if user.is_authenticated %}
            <p>
                {% blocktrans %}
                What do you want to do?
                {% endblocktrans %}
            </p>
            {% url "contact_list" as contacts_url %}
            {% url "oresource_list" as oresource_list %}
            {% url "oresource_create" as oresource_create %}
            {% blocktrans %}
                <a href="{{ contacts_url }}" class="btn btn-primary large">Contacts</a>
                <a href="{{ oresource_list }}" class="btn btn-primary large">View Resource Records</a>
                <a href="{{ oresource_create }}" class="btn btn-primary large">Create Resource Records</a>
            {% endblocktrans %}
            {% else %}
            <p>
                {% url "account_login" as login_url %}
                {% blocktrans %}
                    Login to get started.
                    <a href="{{ login_url }}" class="btn btn-default">Log In</a>
                {% endblocktrans %}
            </p>
            {% endif %}
        </div>
    </section>
{% endblock %}

td/templates/publishing/oresource_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{{ officialresource.language }} Official Resource {{ officialresource.resource_type }}{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li><a href="{% url "oresource_list" %}">{% trans "Official Resources" %}</a></li>
        <li>{{ officialresource.language }}</li>
    </ul>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        {{ officialresource.language }}
                    </h2>
                </div>
                <div class="panel-body">
                    {{ officialresource.resource_type }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

td/templates/publishing/oresource_form.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{% if lang %}Update{% else %}Create{% endif %} Official Resource{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li><a href="{% url "oresource_list" %}">{% trans "Official Resources" %}</a></li>
        <li>{% if lang %}Update{% else %}Create{% endif %} Official Resource</li>
    </ul>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        {% if lang %}Update{% else %}Create{% endif %} Official Resource{% if lang %} for {{ lang.name }}{% endif %}
                    </h2>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <button type="submit" class="btn btn-primary pull-right">
                            {% if lang %}Update{% else %}Create{% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block extra_script %}
    <script>
    $(function() {

        $('#id_publish').click(function() {
            var disable = !this.checked;
            $('#id_checking_level').attr('disabled', disable);
            $('#id_checking_entity').attr('disabled', disable);
            $('#id_version').attr('disabled', disable);
        });
    });
    </script>
{% endblock %}

td/templates/publishing/oresource_list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{% trans "Official Resources" %}{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li>{% trans "Official Resources" %}</li>
    </ul>

    <div class="panel panel-default">
        <div class="panel-heading panel-heading-with-table">
            <h2 class="panel-title">{% trans "Publish Requests" %}</h2>
        </div>
        {% if publish_requests %}
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th></th>
                        <th>Requestor</th>
                        <th>Resource</th>
                        <th>Language</th>
                        <th>Checking Level</th>
                        <th>Contributors</th>
                        <th>Created at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pr in publish_requests %}
                        <tr>
                            {% include "publishing/_pr_row_data.html" with pr=pr %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="panel-body">None</div>
        {% endif %}
        <div class="panel-heading panel-heading-with-table">
            <a href="{% url "oresource_create" %}" class="btn btn-xs btn-primary pull-right">
                <i class="fa fa-plus"></i>
                Add
            </a>
            <h2 class="panel-title">{% trans "Official Resources" %}</h2>
        </div>
        {% if object_list %}
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th></th>
                        <th>Language</th>
                        <th>Contact</th>
                        <th>Date Started</th>
                        <th>Notes</th>
                        <th>Offline</th>
                        <th>Publish Date</th>
                        <th>Version</th>
                        <th>Source</th>
                        <th>Checking Entity</th>
                        <th>Checking Level</th>
                    </tr>
                </thead>
                <tbody>
                    {% for oresource in object_list %}
                        <tr>
                            {% include "publishing/_oresource_row_data.html" %}
                        </tr>
                        {% for version in oresource.versions %}
                            <tr class="version">
                                {% include "publishing/_oresource_row_data.html" with oresource=version.object_version.object %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="panel-body">None, <a href="{% url "oresource_create" %}">add one</a>!</div>
        {% endif %}
    </div>

{% endblock %}

td/templates/publishing/publishrequest_confirm_delete.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}Request Publication{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        Reject a Request a Publication
                    </h2>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Are you sure you want to Reject (delete) this request for publication: ({{ object.pk }}) {{ object.resource_type }} in ({{ object.language.code }}) {{ object.language.name }}</p>
                        <div class="actions pull-right">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                            <a href="{% url "publish_request_update" object.pk %}" class="btn btn-danger">Cancel</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

td/templates/publishing/publishrequest_form.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}Request Publication{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        Request a Publication
                    </h2>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        {% if form.instance.pk %}
                            <div>
                            <ul class="list-unstyled">
                                {% for la in form.instance.licenseagreement_set.all %}
                                    <li><a href="{{ la.document.url }}" class="btn btn-primary"><i class="fa fa-paperclip"></i> View</a> {{ la.document.name }}</li>
                                {% endfor %}
                            </ul>
                            </div>
                            <div class="actions pull-right">
                              <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Approve</button>
                              <a href="{% url "publish_request_delete" form.instance.pk %}" class="btn btn-warning"><i class="fa fa-ban"></i> Reject</a>
                            </div>
                        {% else %}
                        <button type="submit" class="btn btn-primary pull-right">
                            {% if form.errors %}
                                Re-Submit
                                {% else %}
                            Submit
                                {% endif %}
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
{% endblock %}